app = 'habbittracker'
primary_region = 'yyz'

[build]

[env]
  DB_PATH = '/data/habits.db'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'

[mounts]
  source = 'habbittracker_data'
  destination = '/data'
